services:
  expense-db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - expense_data:/var/lib/postgresql/data

  service:
    build: ./
    container_name: distributed_api
    env_file:
      - .env
    ports:
    - "8000:8000"
    depends_on:
      - expense-db
      
  
  
volumes:
  expense_data:
